workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BEFORE_SHA !~ /0{40}/'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

variables:
  CONTAINER_LATEX_IMAGE: $CI_REGISTRY/bigouden/alpine-latex:daily
  CONTAINER_SMTP_IMAGE: alpine:latest
  LATEX_FILES_DIRECTORY: $CI_PROJECT_DIR

include:
  - project: 'Bigouden/gitlab-ci-templates'
    file: '.gitlab-ci-common.yml'

Compile:
  stage: Build
  image:
    name: $CONTAINER_LATEX_IMAGE
    entrypoint: [""]
  before_script:
    - cd $LATEX_FILES_DIRECTORY || true
  script:
    - latexmk -pdf *.tex
  dependencies: []
  artifacts:
    paths:
      - "$LATEX_FILES_DIRECTORY/*.pdf"
  when: always

Send Email:
  stage: Notify
  image: $CONTAINER_SMTP_IMAGE
  before_script:
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
    - apk add --upgrade swaks perl-net-ssleay findutils
    - cd $LATEX_FILES_DIRECTORY || true
  script:
    - swaks --server $SMTP_SERVER --port $SMTP_PORT --tlsc -hs --auth-user $SMTP_USERNAME --auth-password $SMTP_PASSWORD --from "$MAIL_FROM" --to "$MAIL_TO" -h-Subject "$MAIL_SUBJECT" --body "$MAIL_BODY" `find . -type f -name '*.pdf' -printf '--attach-type application/pdf --attach-name %f --attach @%f '`
  dependencies:
    - Compile
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $SMTP_SERVER && $SMTP_PORT && $SMTP_USERNAME && $SMTP_PASSWORD && $MAIL_FROM && $MAIL_TO && $MAIL_SUBJECT && $MAIL_BODY && $FILENAME
