variables:
  CONTAINER_GITLEAKS_IMAGE: zricethezav/gitleaks:latest
  CONTAINER_SEMGREP_IMAGE: returntocorp/semgrep:latest

Gitleaks SAST:
  stage: Security
  image: $CONTAINER_GITLEAKS_IMAGE
  script:
    - gitleaks detect --source . -v

Semgrep SAST:
  stage: Security
  image: $CONTAINER_SAST_IMAGE
  script: 
    - semgrep ci --config auto --force-color
