include:
  - project: 'Bigouden/gitlab-ci-templates'
    file: '.gitlab-ci-owasp-zap.yml'

.services:
  services:
    - name: $CONTAINER_TEST_IMAGE
      alias: exporter
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update curl
  variables:
    GIT_STRATEGY: none
  dependencies: []

variables:
  PROMETHEUS_EXPORTER_PORT: "8123"
  OWASP_ZAP_TARGET: http://target:${PROMETHEUS_EXPORTER_PORT}

Prometheus Exporter:
  stage: Test
  extends: .services
  script:
    - curl -f --connect-timeout 60 http://exporter:${PROMETHEUS_EXPORTER_PORT}/metrics
