variables:
  CONTAINER_GITLEAKS_IMAGE: zricethezav/gitleaks:latest
  CONTAINER_SEMGREP_IMAGE: returntocorp/semgrep:latest

Gitleaks SAST:
  stage: Security
  image: 
    name: $CONTAINER_GITLEAKS_IMAGE
    entrypoint: [""]
  script:
    - gitleaks detect --source . -v
  variables:
    GIT_DEPTH: 0

Semgrep SAST:
  stage: Security
  image: $CONTAINER_SEMGREP_IMAGE
  script: 
    - semgrep ci --config auto --force-color
