variables:
  CONTAINER_OWASP_ZAP_IMAGE: ghcr.io/zaproxy/zaproxy:stable

.services_owasp_zap:
  services:
    - name: $CONTAINER_TEST_IMAGE
      alias: target
  image: 
    name: $CONTAINER_OWASP_ZAP_IMAGE
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  dependencies: []

OWASP Zed Attack Proxy:
  stage: Inspect
  extends: .services_owasp_zap
  script:
    - zap-baseline.py -t ${OWASP_ZAP_TARGET}
