variables:
  CONTAINER_CLIENT_IMAGE: alpine:latest
  CONTAINER_GITLEAKS_IMAGE: zricethezav/gitleaks:latest
  CONTAINER_SEMGREP_IMAGE: returntocorp/semgrep:latest

Pylint:
  stage: Quality
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update git py3-pip
    - pip install pylint
  dependencies: []
  script:
    - find . -type f -name "*.py" | xargs pylint 
  rules:
    - exists:
        - "**/*.py"

Gitleaks:
  stage: Security
  image: 
    name: $CONTAINER_GITLEAKS_IMAGE
    entrypoint: [""]
  script:
    - gitleaks detect --source . -v
  variables:
    GIT_DEPTH: 0

Semgrep:
  stage: Security
  image: $CONTAINER_SEMGREP_IMAGE
  script: 
    - semgrep ci --config auto --force-color
