variables:
  CONTAINER_CLIENT_IMAGE: alpine:latest
  CONTAINER_GITLEAKS_IMAGE: zricethezav/gitleaks:latest
  CONTAINER_SEMGREP_IMAGE: returntocorp/semgrep:latest
  CONTAINER_ANSIBLE_IMAGE: $CI_REGISTRY/bigouden/alpine-ansible:daily
  CONTAINER_ANSIBLE_LATER_IMAGE: thegeeklab/ansible-later:latest
  CONTAINER_KICS_IMAGE: checkmarx/kics:latest
  CONTAINER_TRIVY_IMAGE: aquasec/trivy:latest
  GIT_DEPTH: 1

Ansible Lint:
  stage: Quality
  needs: []
  image: 
    name: $CONTAINER_ANSIBLE_IMAGE
    entrypoint: ['']
  script:
    - ansible-lint
  variables:
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
  rules:
    - exists:
        - "**/ansible.cfg"
        - "**/hosts"
        - "**/.ansible-lint"
        - "**/.later.yml"

Ansible Later:
  stage: Quality
  needs: []
  image: 
    name: $CONTAINER_ANSIBLE_LATER_IMAGE
    entrypoint: ['']
  script:
    - ansible-later **/*.yml
  rules:
    - exists:
        - "**/ansible.cfg"
        - "**/hosts"
        - "**/.ansible-lint"
        - "**/.later.yml"

Kics:
  stage: Security
  needs: []
  image: 
    name: $CONTAINER_KICS_IMAGE
    entrypoint: ['']
  script:
    - kics scan -p .
  rules:
    - exists:
        - "**/ansible.cfg"
        - "**/hosts"
        - "**/.ansible-lint"
        - "**/.later.yml"

Trivy Configuration:
  stage: Security
  needs: []
  image:
    name: $CONTAINER_TRIVY_IMAGE
    entrypoint: ['']
  script:
    - trivy config .
  rules:
    - exists:
        - "**/Dockerfile"

Trivy Repository:
  stage: Security
  needs: []
  image:
    name: $CONTAINER_TRIVY_IMAGE
    entrypoint: ['']
  before_script:
    - 'trivy repo --download-db-only --insecure'
  script:
    - trivy repo --exit-code 1 --severity CRITICAL "$CI_REPOSITORY_URL"
  variables:
    GIT_STRATEGY: none

Pylint:
  stage: Quality
  needs: []
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update git py3-pip
    - pip install pylint
  dependencies: []
  script:
    - find . -type f -name "*.py" | xargs pylint 
  rules:
    - exists:
        - "**/*.py"

Shellcheck:
  stage: Security
  needs: []
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update shellcheck
  dependencies: []
  script:
    - find . -type f -name "*.sh" | xargs shellcheck 
  rules:
    - exists:
        - "**/*.sh"

Gitleaks:
  stage: Security
  needs: []
  image: 
    name: $CONTAINER_GITLEAKS_IMAGE
    entrypoint: [""]
  script:
    - gitleaks detect --source . -v
  variables:
    GIT_DEPTH: 0

Semgrep:
  stage: Security
  needs: []
  image: $CONTAINER_SEMGREP_IMAGE
  script: 
    - semgrep ci --config auto --force-color
