.services:
  services:
    - name: $CONTAINER_TEST_IMAGE
      alias: exporter
      command: $PROMETHEUS_EXPORTER_COMMAND
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update curl
  variables:
    GIT_STRATEGY: none
  dependencies: []

variables:
  PROMETHEUS_EXPORTER_PORT: "8123"
  PROMETHEUS_EXPORTER_COMMAND:
    - ""

Prometheus Exporter:
  stage: Test
  extends: .services
  script:
    - curl -f --connect-timeout 60 http://exporter:${PROMETHEUS_EXPORTER_PORT}/metrics
