variables:
  CONTAINER_LATEX_IMAGE: registry.gitlab.com/bigouden/alpine-latex:latest
  CONTAINER_SMTP_IMAGE: alpine:edge

Compile:
  stage: Build
  image:
    name: $CONTAINER_LATEX_IMAGE
    entrypoint: [""]
  script:
    - latexmk -pdf $FILENAME.tex
  artifacts:
    paths:
      - $FILENAME.pdf
  when: always

Send Email:
  stage: Notify
  image: $CONTAINER_SMTP_IMAGE
  before_script:
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
    - apk add --upgrade swaks perl-net-ssleay
  script:
    - swaks --server $SMTP_SERVER --port $SMTP_PORT -tlsos -hs --auth-user $SMTP_USERNAME --auth-password $SMTP_PASSWORD --from "$MAIL_FROM" --to "$MAIL_TO" -h-Subject "$MAIL_SUBJECT" --body "$MAIL_BODY" --attach-name $FILENAME.pdf --attach @$FILENAME.pdf
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $SMTP_SERVER && $SMTP_PORT && $SMTP_USERNAME && $SMTP_PASSWORD && $MAIL_FROM && $MAIL_TO && $MAIL_SUBJECT && $MAIL_BODY && $FILENAME
      when: on_success